# Inputs

inputs = {}

inputs["conservation_area_csv"] = "./input-data/conservation_area.csv"
inputs["flood_risk_area_csv"] = "./input-data/flood_risk_area.csv"
inputs["greenbelt_csv"] = "./input-data/greenbelt.csv"
inputs["highway_coverage_csv"] = "./input-data/highway_coverage.csv"
inputs["historical_conservation_csv"] = "./input-data/historical_conservation.csv"
inputs["HA_bus_csv"] = "./input-data/housing_accessibility_by_bus.csv"
inputs["HA_rail_csv"] = "./input-data/housing_accessibility_by_rail.csv"
inputs["HA_road_csv"] = "./input-data/housing_accessibility_by_road.csv"
inputs["JA_bus_csv"] = "./input-data/job_accessibility_by_bus.csv"
inputs["JA_rail_csv"] = "./input-data/job_accessibility_by_rail.csv"
inputs["JA_road_csv"] = "./input-data/job_accessibility_by_road.csv"
inputs["national_nature_reserves_csv"] = "./input-data/national_nature_reserves.csv"
inputs["ONB_csv"] = "./input-data/outstanding_natural_beauty.csv"
inputs["parks_and_gardens_csv"] = "./input-data/parks_and_gardens.csv"
inputs["population_density_csv"] = "./input-data/population_density.csv"
inputs["proximity_to_green_space_csv"] = "./input-data/proximity_to_green_space.csv"
inputs["special_scientific_interest_csv"] = "./input-data/special_scientific_interest.csv"
inputs["slope_csv"] = "./input-data/slope.csv"
inputs["surface_water_csv"] = "./input-data/surface_water.csv"
inputs["coordinates_csv"] = "./input-data/coordinates.csv"
inputs["correlation_matrix_csv"] = "./input-data/correlation-dd.csv"

# Outputs
outputs = {}

outputs["Conservation_Areas"] = "./output-data/Conservation_Areas.png"
outputs["Flood_Risk_Areas"] = "./output-data/Flood_Risk_Areas.png"
outputs["Greenbelt"] = "./output-data/Greenbelt.png"
outputs["Highway_Coverage"] = "./output-data/Highway_Coverage.png"
outputs["Historical_Conservation"] = "./output-data/Historical_Conservation.png"
outputs["Housing_Accessibility_by_Bus"] = "./output-data/Housing_Accessibility_by_Bus.png"
outputs["Housing_Accessibility_by_Rail"] = "./output-data/Housing_Accessibility_by_Rail.png"
outputs["Housing_Accessibility_by_Road"] = "./output-data/Housing_Accessibility_by_Road.png"
outputs["Job_Accessibility_by_Bus"] = "./output-data/Job_Accessibility_by_Bus.png"
outputs["Job_Accessibility_by_Rail"] = "./output-data/Job_Accessibility_by_Rail.png"
outputs["Job_Accessibility_by_Road"] = "./output-data/Job_Accessibility_by_Road.png"
outputs["National_Nature_Reserves"] = "./output-data/National_Nature_Reserves.png"
outputs["Areas_of_Outstanding_Natural_Beauty"] = "./output-data/Areas_of_Outstanding_Natural_Beauty.png"
outputs["Parks_and_Gardens"] = "./output-data/Parks_and_Gardens.png"
outputs["Population_Density"] = "./output-data/Population_Density.png"
outputs["Proximity_to_Green_Space"] = "./output-data/Proximity_to_Green_Space.png"
outputs["Special_Scientific_Interest"] = "./output-data/Special_Scientific_Interest.png"
outputs["Slope"] = "./output-data/Slope.png"
outputs["Surface_Water"] = "./output-data/Surface_Water.png"
outputs["Weights_equal"] = "./output-data/Weights_equal.csv"
outputs["Av_weights_map_values"] = "./output-data/Av_weights_values.csv"
outputs["Av_weights_map"] = "./output-data/Av_weights_map.png"
outputs["Weights_hierarchical"] = "./output-data/Weights_hierarchical.csv"
outputs["Hierarchical_weights_map_values"] = "./output-data/Hierarchical_weights_map_values.csv"
outputs["Hierarchical_weights_map"] = "./output-data/Hierarchical_weights_map.png"
outputs["Hierarchical_weights_cube_map"] = "./output-data/Hierarchical_weights_cube_map.png"
outputs["Weights_cor"] = "./output-data/Weights_cor.csv"
outputs["Weights_cor_map_values"] = "./output-data/Weights_cor_map_values.csv"
outputs["Weights_cor_map"] = "./output-data/Weights_cor_map.png"
outputs["Weights_cor_cube_map_values"] = "./output-data/Weights_cor_cube_map_values.csv"
outputs["Weights_cor_cube_map"] = "./output-data/Weights_cor_cube_map.png"
outputs["Dendrogram"] = "./output-data/Dendrogram.png"
outputs["Correlation_matrix"] = "./output-data/Correlation_matrix.png"